Completed prep-css-flexbox exercise.
meganbmartinez/prep-1121-code-solutions pull request #8
Opened 2021-11-12 12:18 UTC by meganbmartinez

![1) Display Flex Screenshot 2021-11-11 223839](https://user-images.githubusercontent.com/6316645/141465879-007fbad6-b025-4dc4-8f85-99542c64488d.png)
![2) Flex-Wrap Screenshot 2021-11-11 224039](https://user-images.githubusercontent.com/6316645/141465887-af952327-c8a1-4eb2-bcda-e6ea16b9e556.png)
![3) Justify-Content Screenshot 2021-11-12 041255](https://user-images.githubusercontent.com/6316645/141465897-66c73a94-d919-418d-b135-4c3465c03827.png)

![4) Align-Items Screenshot 2021-11-12 040831](https://user-images.githubusercontent.com/6316645/141465908-0d999e05-635b-4415-92fd-f31089af4d23.png)

2021-11-12 23:41 UTC, thebearingedge requested changes
Hi Megan, this might look like a large review, but some of the suggestions are very similar. Please let me know if I can help out!

2021-11-12 23:41 UTC, thebearingedge commented on prep-css-flexbox/align-items.html
> +      .card-deck {
Try using an `id` selector here (`#card-deck`).

2021-11-12 23:41 UTC, thebearingedge commented on prep-css-flexbox/align-items.html
> +        justify-content: center;
You should be able to remove the `display`, `align-items`, and `justify-content` properties from the `.card-container` and still achieve the desired effect. Although, the `min-height` should be moved to your `#card-deck`.

2021-11-12 23:41 UTC, thebearingedge commented on prep-css-flexbox/flex-wrap.html
> +        flex-wrap: wrap;
For this part of the assignment, you'll want to put `display` and `flex-wrap` into a rule set that selects the `#card-deck`.

2021-11-12 23:41 UTC, thebearingedge commented on prep-css-flexbox/justify-content.html
> +      .card-deck {
For this rule set, we'll want to use an id selector like `#card-deck`.

2021-11-13 00:44 UTC, meganbmartinez commented
![1) Align Items Screenshot 2021-11-12 162149](https://user-images.githubusercontent.com/6316645/141598825-a6f84ebc-1e74-4762-ab8b-bb1e84420274.png)
![2) Flex Wrap Screenshot 2021-11-12 162149](https://user-images.githubusercontent.com/6316645/141598834-f59df6a1-2f8e-4c4b-807e-8050a2025c4f.png)
![3) Justify Content Screenshot 2021-11-12 163546](https://user-images.githubusercontent.com/6316645/141598866-540f559a-d8b1-4815-9a5e-c6947990ab71.png)

2021-11-13 16:32 UTC, thebearingedge approved these changes
Much better 👍

2021-11-13 17:46 UTC, merged